version: '3.8'
services:
  app:
    container_name: golang_openapi_playground
    build: .
    ports:
      - 8787:1323
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testdb
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbpass
    volumes:
      - ./data:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
