openapi: 3.0.0
info:
  title: golang_openapi_playground
  version: 1.0.0
paths:
  /tasks:
    get:
      operationId: getTasks
      summary: Get all tasks
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Task'
    post:
      operationId: createTask
      summary: Create a task
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaskForCreate'
      responses:
        '201':
          description: Created
    put:
      operationId: updateTask
      summary: Update a task
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Task'
      responses:
        '204':
          description: No Content
    patch:
      operationId: partiallyUpdateTask
      summary: Partially update a task
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Task'
      responses:
        '204':
          description: No Content

  /tasks/{id}:
    delete:
      operationId: deleteTask
      summary: Delete a task
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: No Content

components:
  schemas:
    Task:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
        completed:
          type: boolean

    TaskForCreate:
      type: object
      properties:
        title:
          type: string
        completed:
          type: boolean
